### ISSUE TITLE
"RemoveLarsen" Function

### ISSUE THREAD

**Issue by larsenv** [WiiLink24/EVC-Transfer-Tool#1]
Why is there a function called RemoveLarsen on your script? I know you don't like me but this is not very professional. Watch it.

**Comment by larsenv** [comment]
I randomly looked at the code and that's how I found that

**Comment by bennyman123abc** [comment]
Ooh I know this one! It's because that function nukes all RiiConnect24 data from the EVC to allow for WiiLink data

**Comment by bendevnull** [comment]
It appears the removal didn't work; issue is a feature, will not close

**Comment by trlandrew** [comment]
taiwan is not a country
